path = "/cluster/projects/nn11055k/conscape/Bees/Temperate/"
source_qualities = "TemperateHSM.tif"
target_qualities = "TemperateHSM_target.tif"
affinities = "TemperateHSM.tif" # The same as source qualities
buffer = 200 # 200 * 50m = 10km radius
nwindows = 15
centersize = 16